### ISSUE TITLE
Updates for Article Publication

### ISSUE THREAD

**Issue by ZoeLeBlanc** [rlskoeser/shxco-missingdata-specreading#5]
Trying to get ducks in order for this article's publication/putting it on arXiv 🥳 

Ideally we would try do all of the following, though might prioritize some of these issues. Also happy to take the lead on this:

- [x] Reorganize code to make it easier to recreate figures for others looking to replicate our approach
    Need to create/edit notebooks for the following paper sections:
    - [x] Missing Membership Activities Section Figures
    - [x] Missing Members Section Figures
    - [x] #6
    - [x] Missing Books Section Figures
    - [x] #7
- [ ] Create an appendix folder for validation code and some of the code that didn't make into the paper
     - [x]  Prophet validation
     - [x] Lenskit validation
     - [x] Exceptional borrowers metadata explorations
     - [x] Link prediction work
     - [x] #8 
     - [ ] Anything else?
 - [x] add/update readmes
     - [x] add new sections to main readme (appendix, scripts)
     - [x] add readme to appendix folder
- [x] #10

**Comment by rlskoeser** [comment]
I have a google doc where I was making notes of which figures are generated from which notebooks https://docs.google.com/document/d/1ByEnw251aidO7vFT3BBKptPS7LBHDiviY363aVykEwA/edit#heading=h.hkmwfss2mhbv

Maybe we can make a version of this as a readme somewhere in this repo.

**Comment by ZoeLeBlanc** [comment]
Oh I should've remembered that Google Doc 😅 ! Think we could definitely add it in, though I am trying to update the READMEs to indicate what figures are generating from where so also could just do that as we move through the code reorganization.

**Comment by rlskoeser** [comment]
Agreed. We can use the google doc as a reference where useful and improve/update the documentation in this repo so it corresponds to the reorganized notebooks, but eventually it will be out of date and this repo will be the real reference.
